export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';

export const SEARCH_FOR_VIDEOS = 'SEARCH_FOR_VIDEOS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';

export const FETCH_VIDEO_DETAILS = 'FETCH_VIDEO_DETAILS';
export const RECEIVE_VIDEO_DETAILS = 'RECEIVE_VIDEO_DETAILS';

export const SET_CONTENT_FILTER = 'SET_CONTENT_FILTER';

export const NAVIGATE_TO_NEXT_PAGE = 'NAVIGATE_TO_NEXT_PAGE';
export const NAVIGATE_TO_PREV_PAGE = 'NAVIGATE_TO_PREV_PAGE';

export const SET_PREV_PAGE_TOKEN = 'SET_PREV_PAGE_TOKEN';
export const SET_NEXT_PAGE_TOKEN = 'SET_NEXT_PAGE_TOKEN';

export const RESET_PAGE_TOKEN = 'RESET_PAGE_TOKEN';
